app:
  scrapper:
    scheduler:
      interval: 15s
      force-check-delay: 30s
      thread-pool-size: 4
    github:
      token: ${GITHUB_TOKEN} # env variable
      url: https://api.github.com
    stackoverflow:
      url: https://api.stackexchange.com/2.3
      key: ${SO_TOKEN_KEY}
      access-token: ${SO_ACCESS_TOKEN}
    bot-url: http://localhost:8080
  database:
    access-type: SQL
    page-size: 1000

spring:
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
  application:
    name: Scrapper
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
