server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

app:
  scrapper:
    scheduler:
      interval: 15s
      force-check-delay: 30s
      thread-pool-size: 4
    github:
      token: ${GITHUB_TOKEN}
      url: https://api.github.com
    stackoverflow:
      url: https://api.stackexchange.com/2.3
      key: ${SO_TOKEN_KEY}
      access-token: ${SO_ACCESS_TOKEN}
    bot-url: http://localhost:8080
  database:
    page-size: 1000

kafka:
  properties:
    bootstrap-servers: localhost:9092
    retry-policy:
      interval: 1000
      multiplier: 2.0
      maxDelay: 10000
      max-attempts: 3
      auto-create-topics: true
    consumer:
      enable-auto-commit: false
      ack-mode: manual
      auto-offset-reset: earliest
      trusted-packages: "*"
    producer:
      client-id: common-kafka-sender
      enable-idempotence-config: true
      acks-config: all
  consumers:
    client-listener:
      group-id: client-consumer-group
      topic: client-listener-topic-request
      concurrency: 2
    link-listener:
      group-id: link-consumer-group
      topic: link-listener-topic-request
      concurrency: 2
  producers:
    common-sender:
      topic: link-topic-response

spring:
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
    driver-class-name: org.postgresql.Driver
  application:
    name: backend-processor
  liquibase:
    enabled: true
    change-log: classpath:db/migrations/master.xml
