server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

app:
  telegram-enabled: false
  telegram-token: ${TELEGRAM_TOKEN:}
  scrapper-url: ${SCRAPPER_URL}

spring:
  application:
    name: frontend-message-processor
