server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

app:
  telegram-token: ${TELEGRAM_TOKEN} # env variable
  scrapper-url: ${SCRAPPER_URL}

spring:
  application:
    name: frontend-message-processor
