apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topic-bootstrap
  namespace: devpulse-staging
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: topic-bootstrap
          image: confluentinc/cp-kafka:7.8.0
          command:
            - /bin/bash
            - -c
            - |
              kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic link-updates --partitions 2 --replication-factor 1
              kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic client-listener-topic-request --partitions 2 --replication-factor 1
              kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic link-listener-topic-request --partitions 2 --replication-factor 1
              kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic link-topic-response --partitions 2 --replication-factor 1
