apiVersion: v1
kind: Secret
metadata:
  name: devpulse-secrets
  namespace: devpulse-staging
type: Opaque
stringData:
  INTERNAL_SHARED_SECRET: "replace-me"
  GITHUB_TOKEN: "replace-me"
  SO_TOKEN_KEY: "replace-me"
  SO_ACCESS_TOKEN: "replace-me"
  BOT_POSTGRES_USER: "postgres"
  BOT_POSTGRES_PASSWORD: "postgres"
  BOT_POSTGRES_DB_NAME: "devpulse_bot"
  SCRAPPER_POSTGRES_USER: "postgres"
  SCRAPPER_POSTGRES_PASSWORD: "postgres"
  SCRAPPER_POSTGRES_DB_NAME: "devpulse_scrapper"
